services: docker
language: bash
env:
    global:
      - DOCKER_REPO=meyskens/firefox-pulseaudio
    matrix:
      - ARCH=amd64
      - ARCH=armhf
      - ARCH=arm64v8

jobs:
  include:
    - stage: build
      install:
        - docker run --rm --privileged multiarch/qemu-user-static:register
      script:
        - docker build --build-arg="ARCH=$ARCH"
    - stage: manifest
      script:
        - echo "TO DO"
