services: docker
language: bash
env:
  global:
    - DOCKER_REPO=meyskens/firefox-pulseaudio
jobs:
  include:
    - stage: build
      env:
        - ARCH=amd64
      install: &_install
        - docker run --rm --privileged multiarch/qemu-user-static:register
      script: &_script
        - docker build --build-arg="ARCH=$ARCH" -t $DOCKER_REPO:$ARCH-latest ./

    - stage: build
      env:
        - ARCH=armhf
      install: *_install
      script: *_script
    - stage: build
      env:
        - ARCH=arm64v8
      install: *_install
      script: *_script
    - stage: manifest
      script:
        - echo "TO DO"
