name: Docker Image Publish

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 0 * * 1

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, armhf, arm64v8]
    steps:
    - uses: actions/checkout@v1
    - name: Get qemu-user-static
      run: sudo apt-get update && sudo apt-get install -y qemu-user-static
    - name: Configure Docker
      run: |
        echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
        sudo service docker restart
        docker run --rm --privileged multiarch/qemu-user-static:register
    - name: Build the Docker image
      run: |
        if [[ "$ARCH" == "amd64" ]]; then export QEMU_BIN="qemu-x86_64-static"; fi
        if [[ "$ARCH" == "armhf" ]]; then export QEMU_BIN="qemu-arm-static"; fi
        if [[ "$ARCH" == "arm64v8" ]]; then export QEMU_BIN="qemu-aarch64-static"; fi
        cp /usr/bin/$QEMU_BIN ./
        docker build . --build-arg="ARCH=$ARCH" --build-arg="QEMU_BIN=$QEMU_BIN" --squash --file Dockerfile --tag docker.pkg.github.com/meyskens/docker-firefox-pulseaudio/firefox:${{ matrix.arch }}-latest
      env:
        ARCH: ${{ matrix.arch }}
        DOCKER_CLI_EXPERIMENTAL: enabled
    - name: Log in to registry
      uses: actions/docker/login@master
      env:
        DOCKER_REGISTRY_URL: docker.pkg.github.com
        DOCKER_USERNAME: ${{ github.actor }}
        DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
    - name: Push image
      run: docker push docker.pkg.github.com/meyskens/docker-firefox-pulseaudio/firefox:${{ matrix.arch }}-latest
  publish-manifest:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Configure Docker
        run: |
          echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
          sudo service docker restart
          docker run --rm --privileged multiarch/qemu-user-static:register
      - name: Log in to registry
        uses: actions/docker/login@master
        env:
          DOCKER_REGISTRY_URL: docker.pkg.github.com
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Manifest 
        run: |
          docker manifest create $DOCKER_REPO:latest $DOCKER_REPO:amd64-latest $DOCKER_REPO:armhf-latest $DOCKER_REPO:arm64v8-latest
          docker manifest annotate $DOCKER_REPO:latest $DOCKER_REPO:amd64-latest --arch amd64
          docker manifest annotate $DOCKER_REPO:latest $DOCKER_REPO:armhf-latest --arch arm --variant v7
          docker manifest annotate $DOCKER_REPO:latest $DOCKER_REPO:arm64v8-latest --arch arm64 --variant armv8
          docker manifest push $DOCKER_REPO:latest
        env:
          DOCKER_REPO: docker.pkg.github.com/meyskens/docker-firefox-pulseaudio/firefox
          DOCKER_CLI_EXPERIMENTAL: enabled
